### ISSUE TITLE
Possible design change: provide "smart" constructors under different names

### ISSUE THREAD

**Issue by 97jaz** [97jaz/datetime-lib#1]
@jackfirth If you saw my recent post to the racket-users mailing list, you know that I'm struggling with trying to get custom struct constructors, match expanders, and contract boundaries all playing nicely together. I'm beginning to think that I'm just trying to fight too much against Racket's preferred way of doing things.

So what do you think about providing the "smart" constructors under different names? Like `make-date`, `make-datetime`, etc.? The default constructors would also be provided. In the case of `date` and `time`, this is kind of silly, since the smart constructors only differ from the default ones in that they provide default field values. So, for example, you could use `(make-date 2000)` as opposed to `(date 2000 1 1)`. 

In the case of `datetime`, however, both constructors are actually useful. The smart constructor would take a year, month, day, hour, etc., while the default one would take a `date` and a `time` and combine them.

**Comment by jackfirth** [comment]
This can be done with some macro hackery - [`make-struct-info`](http://docs.racket-lang.org/reference/structinfo.html?q=contract-out#%28def._%28%28lib._racket%2Fstruct-info..rkt%29._make-struct-info%29%29) allows creating the structure information binding and specifying what the constructors and accessors are directly. I think you should be able to define a struct with `#:omit-define-syntaxes` and `#:constructor-id`, then use `make-struct-info` to make the struct name use the smart constructor:

``` racket

(struct foo (a b) #:transparent #:omit-define-syntaxes #:constructor-name make-foo)
;; make-foo is bound to a procedure
;; struct:foo is bound to a struct type descriptor
;; foo-a and foo-b are bound to usual accessors
;; foo by itself is unbound
(define (make-foo-smart #:a a #:b b) (make-foo a b))
(define-syntax foo
  (make-struct-info
     (λ () (list #'struct:foo ;; struct type descriptor identifier
                 #'make-foo-smart ;; constructor identifier
                 #'foo? ;; predicate identifier
                 (list #'foo-b #'foo-a) ;; reverse-ordered list of field identifiers
                 (list #f #f) ;; reverse-ordered list of field mutators (immutable, so #f)
                 #t)))) ;; no known supertype
;; now foo is bound to struct info at transform time and expands to make-foo-smart
;; it can be used as a constructor and match expander
(match (foo #:a 1 #:b 2)
  [(foo a b) (list a b)])
```

I have only commented this code, not run it.

**Comment by jackfirth** [comment]
In general, I'm against two different constructors. I think I would prefer the smart constructor have keyword arguments like #:year, #:month, #:minutes, etc. as well as keyword arguments for #:date and #:time so it can be constructed both ways. Or at least I would prefer that approach to two different date constructors.

**Comment by 97jaz** [comment]
Okay, so after I wrote this, I realized that it won't help anyhow. `(contract-out (struct ...))` doesn't support dependent struct field contracts anyway, so there's really no point. It just seems like contracts and the dual-purpose struct id don't play well together.

**Comment by 97jaz** [comment]
As for the constructor, I'm not a big fan of functions that accept disjoint sets of keyword arguments, if only because the built-in support for it in racket is lacking. For example, `case-lambda` doesn't allow keyword arguments, and the `->case` contract constructor doesn't either. A function like the one you describe would have to do quite a lot of its own input validation (e.g., you can't specify `#:month` without `#:year`, but you can do the reverse).

**Comment by 97jaz** [comment]
Wow, I've managed to confuse myself. Regarding the comment two above this one: obviously, there's no requirement to use `(contract-out (struct...))`. I can just give each function its own contract separately, as I did in Gregor. So I may be able to put your example to use, after all. Thanks!

**Comment by jackfirth** [comment]
I just tested this and hit a problem. Providing the constructor as just a function causes the match expander to not work:

```
#lang racket
(module data racket
  (struct foo (a b) #:transparent #:omit-define-syntaxes #:constructor-name make-foo)
  (define (make-foo-smart #:a a #:b b) (make-foo a b))
  (define-syntax foo
    (make-struct-info
       (λ () (list #'struct:foo
                   #'make-foo-smart
                   #'foo?
                   (list #'foo-b #'foo-a)
                   (list #f #f)
                   #t))))
  (match (foo #:a 1 #:b 2)
    [(foo a b) (list a b)]) ;; works in here
  (provide/contract [foo (-> #:a number? #:b number? foo?)]))
(require 'data)
  (match (foo #:a 1 #:b 2)
    [(foo a b) (list a b)]) ;; doesn't work out here - foo is no longer bound as syntax
```

Drat.

**Comment by 97jaz** [comment]
Oh well -- the approach I suggested on the mailing list (and which Alex Knauth improved upon) works. But it just seems like I'm working against Racket instead of with it.

**Comment by jackfirth** [comment]
I think racket's contract-out could use a `#:constructor-contract` option, that would make this much easier. Might be worth opening an issue.

**Comment by 97jaz** [comment]
[Years later...]

The approach that I took to solve the "smart constructor + match expander" problem is [illustrated in the code](https://github.com/97jaz/datetime-lib/blob/033a96a29d0ad2a16da499a08dbfd7252398306d/datetime/date.rkt#L212).

This topic has come up several times on the ML and in Slack since, and at this point I'm not even certain this is the best approach. But this approach is meant to provide _all_ of the following:
- A custom constructor (not the one provided by the struct defnition)
- The custom constructor has a contract that is enforced at the module boundary
- Proper naming of the constructor in error messages. (Check out the difference between a contract violation in a constructor in `gregor` vs. in this library.)
- A custom match-expander
